Updated Qtilities to build against Qt 4.8.3 (MinGW) 1. In the Pri file, added exceptions rtti to the CONFIG. It seems like this is enabled by default on 4.8.1 but not 4.8.3 2. Added dll to the CONFIG variables for plugins. Without this make fails with an error stating undefined reference to WinMain@16. This seems to be a bug in 4.8.3 since the TEMPLATE = lib should take care of that. Refer to this link for more information: https://bugreports.qt-project.org/browse/QTBUG-27227. These changes were tested with Qt 4.8.1 (MinGW and MSVC)